//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Gameplay/GridSystem/InputActiong.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActiong: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActiong()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActiong"",
    ""maps"": [
        {
            ""name"": ""GridPlacement"",
            ""id"": ""f1515820-de5f-4ded-9569-e8b91f46174c"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d7d820dd-edeb-4660-aef1-7ea113b1a101"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Place"",
                    ""type"": ""Button"",
                    ""id"": ""89096203-3eca-4311-a2ee-08ca83fa6440"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""66a4310a-9a6e-4f73-ae63-84364f9549e7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""64044acc-838f-4281-803a-384f0f2c9351"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""28ba617b-00a2-4d0f-a71f-37029a523c22"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""02eae0f1-11da-4f07-b141-ec2820ee8224"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7706db8d-2ec9-4e9e-a295-2e36f51fef66"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e1757d07-fc10-4a6a-91ef-65b73dea4c1d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Place"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse & Keyboard"",
            ""bindingGroup"": ""Mouse & Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // GridPlacement
        m_GridPlacement = asset.FindActionMap("GridPlacement", throwIfNotFound: true);
        m_GridPlacement_Move = m_GridPlacement.FindAction("Move", throwIfNotFound: true);
        m_GridPlacement_Place = m_GridPlacement.FindAction("Place", throwIfNotFound: true);
    }

    ~@InputActiong()
    {
        UnityEngine.Debug.Assert(!m_GridPlacement.enabled, "This will cause a leak and performance issues, InputActiong.GridPlacement.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GridPlacement
    private readonly InputActionMap m_GridPlacement;
    private List<IGridPlacementActions> m_GridPlacementActionsCallbackInterfaces = new List<IGridPlacementActions>();
    private readonly InputAction m_GridPlacement_Move;
    private readonly InputAction m_GridPlacement_Place;
    public struct GridPlacementActions
    {
        private @InputActiong m_Wrapper;
        public GridPlacementActions(@InputActiong wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_GridPlacement_Move;
        public InputAction @Place => m_Wrapper.m_GridPlacement_Place;
        public InputActionMap Get() { return m_Wrapper.m_GridPlacement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GridPlacementActions set) { return set.Get(); }
        public void AddCallbacks(IGridPlacementActions instance)
        {
            if (instance == null || m_Wrapper.m_GridPlacementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GridPlacementActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Place.started += instance.OnPlace;
            @Place.performed += instance.OnPlace;
            @Place.canceled += instance.OnPlace;
        }

        private void UnregisterCallbacks(IGridPlacementActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Place.started -= instance.OnPlace;
            @Place.performed -= instance.OnPlace;
            @Place.canceled -= instance.OnPlace;
        }

        public void RemoveCallbacks(IGridPlacementActions instance)
        {
            if (m_Wrapper.m_GridPlacementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGridPlacementActions instance)
        {
            foreach (var item in m_Wrapper.m_GridPlacementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GridPlacementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GridPlacementActions @GridPlacement => new GridPlacementActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse & Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    public interface IGridPlacementActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnPlace(InputAction.CallbackContext context);
    }
}
